GET {{host}}/employees/1

###

GET {{host}}/employees/7664

###

GET {{host}}/agencies/66

###

GET {{host}}/agencies/1

###

GET {{host}}/employees/top-earners

###

GET {{host}}/employees/top-earners?agency=Health

###

GET {{host}}/employees/top-earners?agency=Transportation&limit=0

###

GET {{host}}/employees/top-earners?agency=Patrol


###

GET {{host}}/employees?name=Director